import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getDatabase, ref, push, set, onValue, update } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=id=>document.getElementById(id);let authed=sessionStorage.getItem('tr_admin')==='1',moments={},allMessages={},subscribed=false;
const USER_HASH='8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918';
const PASS_HASH='48aef22b5e62edb5aac488c1826658e479684ff481292116b45763d860bdc5be';
async function hash(value){const bytes=new TextEncoder().encode(value);const result=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(result)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function showAuth(){$('loginCard').classList.toggle('hidden',authed);$('adminApp').classList.toggle('hidden',!authed);if(authed&&!subscribed){subscribed=true;subscribe()}}
showAuth();
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';const [u,p]=await Promise.all([hash($('login').value.trim()),hash($('password').value)]);if(u===USER_HASH&&p===PASS_HASH){authed=true;sessionStorage.setItem('tr_admin','1');showAuth()}else $('loginError').textContent='Identifiant ou mot de passe incorrect.'});
$('logout').onclick=()=>{sessionStorage.removeItem('tr_admin');authed=false;showAuth()};
$('finalPreset').onchange=()=>{$('finalText').value=$('finalPreset').value};$('finalText').value=$('finalPreset').value;
$('momentForm').addEventListener('submit',async e=>{e.preventDefault();$('createStatus').textContent='Création en cours…';try{const now=Date.now(),hours=Number($('duration').value);const moment={title:$('title').value.trim(),target:Number($('target').value),intro:$('intro').value.trim(),theme:$('theme').value,startsAt:now,endsAt:now+hours*36e5,finalText:$('finalText').value.trim(),confirmPost:$('confirmPost').checked,confirmDelete:$('confirmDelete').checked,forceFinal:false,createdAt:now};const newRef=push(ref(db,'moments'));await set(newRef,moment);const url=`${location.origin}${location.pathname.replace(/admin\.html$/,'')}?m=${newRef.key}`;$('createStatus').innerHTML=`Moment créé ✨ <a href="${url}" target="_blank">Ouvrir le lien participant</a><br><button type="button" class="secondary" id="copyLink">Copier le lien</button>`;document.getElementById('copyLink').onclick=()=>navigator.clipboard.writeText(url);e.target.reset();$('finalText').value=$('finalPreset').value}catch(err){console.error(err);$('createStatus').textContent='Impossible de créer le moment. Vérifie les règles Firebase.'}});
function subscribe(){onValue(ref(db,'moments'),s=>{moments=s.val()||{};render()});onValue(ref(db,'messages'),s=>{allMessages=s.val()||{};render()})}
function render(){const box=$('momentsList');box.innerHTML='';Object.entries(moments).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)).forEach(([id,m])=>{const count=Object.values(allMessages[id]||{}).filter(x=>x&&!x.deleted).length;const pct=Math.min(100,Math.round(count/Math.max(1,m.target)*100));const url=`${location.origin}${location.pathname.replace(/admin\.html$/,'')}?m=${id}`;const el=document.createElement('div');el.className='moment-admin';el.innerHTML=`<h3>${m.title}</h3><p class="stats">${count} participation(s) active(s) / ${m.target} prévue(s) — ${pct}%</p><p>Fin : ${new Date(m.endsAt).toLocaleString('fr-FR')}</p><div class="row"><a class="secondary" href="${url}" target="_blank">Voir</a><button class="secondary copy">Copier le lien</button><button class="primary force">Lancer la finale</button></div>`;el.querySelector('.copy').onclick=()=>navigator.clipboard.writeText(url);el.querySelector('.force').onclick=()=>update(ref(db,`moments/${id}`),{forceFinal:true});box.appendChild(el)})}
