import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getDatabase, ref, push, set, onValue, update } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=id=>document.getElementById(id);let authed=false,moments={},allMessages={};
async function session(){const r=await fetch('/api/session');const j=await r.json();authed=j.authenticated;showAuth()}
session();
function showAuth(){$('loginCard').classList.toggle('hidden',authed);$('adminApp').classList.toggle('hidden',!authed);if(authed)subscribe()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';const r=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:$('login').value,password:$('password').value})});if(r.ok){authed=true;showAuth()}else $('loginError').textContent='Identifiant ou mot de passe incorrect.'});
$('logout').onclick=async()=>{await fetch('/api/logout',{method:'POST'});authed=false;showAuth()};
$('finalPreset').onchange=()=>{$('finalText').value=$('finalPreset').value};$('finalText').value=$('finalPreset').value;
$('momentForm').addEventListener('submit',async e=>{e.preventDefault();const now=Date.now(),hours=Number($('duration').value);const moment={title:$('title').value.trim(),target:Number($('target').value),intro:$('intro').value.trim(),theme:$('theme').value,startsAt:now,endsAt:now+hours*36e5,finalText:$('finalText').value.trim(),confirmPost:$('confirmPost').checked,confirmDelete:$('confirmDelete').checked,forceFinal:false,createdAt:now};const newRef=push(ref(db,'moments'));await set(newRef,moment);const url=`${location.origin}/?m=${newRef.key}`;$('createStatus').innerHTML=`Moment créé ✨ <a href="${url}" target="_blank">Ouvrir le lien participant</a><br><button type="button" class="secondary" id="copyLink">Copier le lien</button>`;document.getElementById('copyLink').onclick=()=>navigator.clipboard.writeText(url);e.target.reset();$('finalText').value=$('finalPreset').value});
function subscribe(){onValue(ref(db,'moments'),s=>{moments=s.val()||{};render()});onValue(ref(db,'messages'),s=>{allMessages=s.val()||{};render()})}
function render(){const box=$('momentsList');box.innerHTML='';Object.entries(moments).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)).forEach(([id,m])=>{const count=Object.values(allMessages[id]||{}).filter(x=>x&&!x.deleted).length;const pct=Math.min(100,Math.round(count/Math.max(1,m.target)*100));const url=`${location.origin}/?m=${id}`;const el=document.createElement('div');el.className='moment-admin';el.innerHTML=`<h3>${m.title}</h3><p class="stats">${count} participation(s) active(s) / ${m.target} prévue(s) — ${pct}%</p><p>Fin : ${new Date(m.endsAt).toLocaleString('fr-FR')}</p><div class="row"><a class="secondary" href="${url}" target="_blank">Voir</a><button class="secondary copy">Copier le lien</button><button class="primary force">Lancer la finale</button></div>`;el.querySelector('.copy').onclick=()=>navigator.clipboard.writeText(url);el.querySelector('.force').onclick=()=>update(ref(db,`moments/${id}`),{forceFinal:true});box.appendChild(el)})}
