import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getDatabase, ref, get } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';

const params=new URLSearchParams(location.search),momentId=params.get('m');
const app=getApps()[0]||initializeApp(firebaseConfig),db=getDatabase(app);
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
let running=false;

function ensureFlames(){const c=$('cauldron');if(!c||c.querySelector('.flame-field'))return;const field=document.createElement('div');field.className='flame-field';for(let i=0;i<7;i++){const f=document.createElement('span');f.className=`real-flame flame-${i+1}`;field.appendChild(f)}const glow=document.createElement('div');glow.className='cauldron-aura';c.appendChild(glow);c.appendChild(field)}
function clearParticles(){$('particles').innerHTML=''}
function addParticle(kind='ember',slow=false,originX=null,originY=null){const p=document.createElement('span');p.className=`cinematic-particle ${kind}`;p.style.left=originX===null?`${8+Math.random()*84}%`:`${originX}%`;p.style.top=originY===null?(slow?`${8+Math.random()*65}%`:'58%'):`${originY}%`;p.style.setProperty('--dx',`${-170+Math.random()*340}px`);p.style.setProperty('--dy',`${slow?-130-Math.random()*250:-220-Math.random()*420}px`);p.style.setProperty('--rot',`${-540+Math.random()*1080}deg`);p.style.setProperty('--scale',`${.55+Math.random()*1.25}`);p.style.animationDuration=`${slow?5+Math.random()*3.5:2.6+Math.random()*2}s`;p.style.animationDelay=`${Math.random()*.6}s`;$('particles').appendChild(p);setTimeout(()=>p.remove(),9500)}
function shower(kind,count,slow=false){for(let i=0;i<count;i++)setTimeout(()=>addParticle(kind,slow),i*(slow?85:32))}
function firework(x,y,delay=0){for(let i=0;i<24;i++){const p=document.createElement('span');p.className='cinematic-particle firework-ray';p.style.left=`${x}%`;p.style.top=`${y}%`;const angle=(Math.PI*2*i)/24,distance=85+Math.random()*150;p.style.setProperty('--dx',`${Math.cos(angle)*distance}px`);p.style.setProperty('--dy',`${Math.sin(angle)*distance}px`);p.style.animationDelay=`${delay}s`;p.style.animationDuration=`${4.2+Math.random()*1.4}s`;$('particles').appendChild(p);setTimeout(()=>p.remove(),7600)}}
function intensity(level){const c=$('cauldron');c.classList.remove('power-1','power-2','power-3','power-4','react-left','react-right','finale');c.classList.add(`power-${Math.min(4,Math.max(1,level))}`)}
async function react(index,total){const c=$('cauldron');c.classList.remove('react-left','react-right');void c.offsetWidth;c.classList.add(index%2?'react-left':'react-right');const ratio=(index+1)/Math.max(1,total);intensity(1+Math.floor(ratio*3));shower(index%3===0?'spark':'ember',8+Math.floor(ratio*10),false);await sleep(480)}
async function readData(){const [mSnap,msgSnap]=await Promise.all([get(ref(db,`moments/${momentId}`)),get(ref(db,`messages/${momentId}`))]);return{moment:mSnap.val()||{},items:Object.values(msgSnap.val()||{}).filter(x=>x&&!x.deleted)}}
function label(item){return item.anonymous?'Anonyme':item.name||'Anonyme'}
function buildSlides(items){if(items.length<=12)return items.map(item=>({text:`${label(item)}\n\n${item.text||''}`,length:(item.text||'').length}));const slides=[];for(let i=0;i<items.length;i+=2){const pair=items.slice(i,i+2);slides.push({text:pair.map(item=>`${label(item)}\n${item.text||''}`).join('\n\n✦\n\n'),length:pair.reduce((n,item)=>n+(item.text||'').length,0)})}return slides}
function targetDuration(count){if(count<=4)return 34000;if(count<=8)return 42000;if(count<=15)return 52000;return 59000}
function slideDuration(slide,slideCount,targetMs){const fixed=20500;const available=Math.max(9000,targetMs-fixed);const share=available/Math.max(1,slideCount);const reading=slide.length<=60?3400:slide.length<=150?4300:5200;return Math.max(2800,Math.min(reading,share))}
async function intro(text){ensureFlames();clearParticles();$('book').classList.add('hidden');$('cauldron').classList.remove('hidden');$('ceremony').dataset.animation='cauldron';intensity(1);text.textContent='Le chaudron s’éveille…';shower('ember',20,true);await sleep(2200);$('cauldron').classList.add('awake');text.classList.add('fade-out');await sleep(500);text.textContent='';text.classList.remove('fade-out');await sleep(300)}
async function showFinalLine(text,line,duration,className='final-step'){text.classList.add('fade-out');await sleep(420);text.textContent=line;text.className=`ceremonyText ${className}`;await sleep(duration)}
async function finalSequence(text,customFinal){const c=$('cauldron');c.classList.remove('power-1','power-2','power-3','power-4');c.classList.add('finale');text.classList.add('fade-out');await sleep(500);text.textContent='';shower('ember',42,false);await sleep(700);if(customFinal)await showFinalLine(text,customFinal,2200,'final-step');await showFinalLine(text,'Tu es unique.',1600,'final-step emphasis');shower('star',16,true);await showFinalLine(text,'Tu es formidable.',1600,'final-step emphasis');shower('star',24,true);await showFinalLine(text,'Ta présence compte.',1900,'final-step emphasis');text.classList.add('fade-out');await sleep(450);text.textContent='';c.classList.add('bursting');shower('star',58,true);shower('confetti',68,true);firework(20,30,0);firework(78,24,.55);firework(50,16,1.1);firework(32,42,1.65);firework(68,40,2.1);await sleep(1350);text.textContent='Toujours Reliés';text.className='ceremonyText grand-final';await sleep(5200)}
async function play(){if(running||!momentId)return;running=true;const started=Date.now(),ceremony=$('ceremony'),text=$('ceremonyText');ceremony.classList.remove('hidden');$('replay').classList.add('hidden');$('closeCeremony').classList.add('hidden');text.className='ceremonyText';try{const {moment,items}=await readData(),slides=buildSlides(items),target=targetDuration(items.length);await intro(text);if(!slides.length){text.textContent='Même sans mot déposé, ce moment rappelle que le lien existe.';text.classList.add('message-reveal');await sleep(4300)}else{for(let i=0;i<slides.length;i++){const slide=slides[i];await react(i,slides.length);text.classList.remove('message-reveal');text.classList.add('fade-out');await sleep(350);text.textContent=slide.text;text.classList.remove('fade-out');text.classList.add('message-reveal');await sleep(slideDuration(slide,slides.length,target))}}await finalSequence(text,moment.finalText||'Merci d’avoir apporté une partie de toi à ce moment.');const remaining=target-(Date.now()-started);if(remaining>0)await sleep(remaining)}catch(e){console.error(e);text.textContent='La cérémonie n’a pas pu se charger. Réessaie dans un instant.'}finally{running=false;$('replay').classList.remove('hidden');$('closeCeremony').classList.remove('hidden');$('cauldron').classList.remove('awake','power-1','power-2','power-3','power-4','react-left','react-right','finale','bursting')}}
document.addEventListener('click',e=>{const id=e.target?.id;if(id==='playFinal'||id==='replay'){e.preventDefault();e.stopImmediatePropagation();play()}},true);
$('closeCeremony')?.addEventListener('click',e=>{if(!running){e.preventDefault();e.stopImmediatePropagation();$('ceremony').classList.add('hidden');clearParticles()}},true);