import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getDatabase, ref, get } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js';
import { firebaseConfig } from './firebase-config.js';

const params=new URLSearchParams(location.search),momentId=params.get('m');
const app=getApps()[0]||initializeApp(firebaseConfig),db=getDatabase(app);
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
let running=false;
const defaultTexts={opening1:'Ce soir, chacun est arrivé avec son histoire…',opening2:'Des instants légers, ordinaires ou plus difficiles.',opening3:'Ici, chaque émotion peut trouver sa place.',collective:'Vos journées étaient différentes…\n\nmais vos histoires se sont rejointes ici.',closing:'Ce moment s’achève.\n\nCe qui était léger peut continuer de briller.\nCe qui était lourd a trouvé un endroit où se poser.',signature:'Toujours Reliés'};

function ensureFlames(){const c=$('cauldron');if(!c||c.querySelector('.flame-field'))return;const field=document.createElement('div');field.className='flame-field';for(let i=0;i<7;i++){const f=document.createElement('span');f.className=`real-flame flame-${i+1}`;field.appendChild(f)}const glow=document.createElement('div');glow.className='cauldron-aura';c.appendChild(glow);c.appendChild(field)}
function clearParticles(){$('particles').innerHTML=''}
function addParticle(kind='ember',slow=false,originX=null,originY=null){const p=document.createElement('span');p.className=`cinematic-particle ${kind}`;p.style.left=originX===null?`${8+Math.random()*84}%`:`${originX}%`;p.style.top=originY===null?(slow?`${8+Math.random()*65}%`:'58%'):`${originY}%`;p.style.setProperty('--dx',`${-170+Math.random()*340}px`);p.style.setProperty('--dy',`${slow?-130-Math.random()*250:-220-Math.random()*420}px`);p.style.setProperty('--rot',`${-540+Math.random()*1080}deg`);p.style.setProperty('--scale',`${.55+Math.random()*1.25}`);p.style.animationDuration=`${slow?5+Math.random()*3.5:2.6+Math.random()*2}s`;p.style.animationDelay=`${Math.random()*.6}s`;$('particles').appendChild(p);setTimeout(()=>p.remove(),9500)}
function shower(kind,count,slow=false){for(let i=0;i<count;i++)setTimeout(()=>addParticle(kind,slow),i*(slow?85:32))}
function intensity(level){const c=$('cauldron');c.classList.remove('power-1','power-2','power-3','power-4','react-left','react-right','finale','calm');c.classList.add(`power-${Math.min(4,Math.max(1,level))}`)}
async function react(index,total){const c=$('cauldron');c.classList.remove('react-left','react-right');void c.offsetWidth;c.classList.add(index%2?'react-left':'react-right');const ratio=(index+1)/Math.max(1,total);intensity(1+Math.floor(ratio*3));shower(index%3===0?'spark':'ember',8+Math.floor(ratio*10),false);await sleep(430)}
async function readData(){const [mSnap,msgSnap]=await Promise.all([get(ref(db,`moments/${momentId}`)),get(ref(db,`messages/${momentId}`))]);return{moment:mSnap.val()||{},items:Object.values(msgSnap.val()||{}).filter(x=>x&&!x.deleted)}}
function label(item){return item.anonymous?'Anonyme':item.name||'Anonyme'}
function buildSlides(items){if(items.length<=10)return items.map(item=>({text:`${item.emotion||'✨'}  ${label(item)}\n\n${item.text||''}`,length:(item.text||'').length}));const slides=[];for(let i=0;i<items.length;i+=2){const pair=items.slice(i,i+2);slides.push({text:pair.map(item=>`${item.emotion||'✨'}  ${label(item)}\n${item.text||''}`).join('\n\n✦\n\n'),length:pair.reduce((n,item)=>n+(item.text||'').length,0)})}return slides}
function targetDuration(count){if(count<=4)return 36000;if(count<=8)return 44000;if(count<=15)return 53000;return 59000}
function slideDuration(slide,slideCount,targetMs){const fixed=20500;const available=Math.max(9000,targetMs-fixed);const share=available/Math.max(1,slideCount);const reading=slide.length<=60?3400:slide.length<=150?4300:5200;return Math.max(2800,Math.min(reading,share))}
async function showLine(text,line,duration,className='narrative-line'){text.classList.add('fade-out');await sleep(380);text.textContent=line;text.className=`ceremonyText ${className}`;await sleep(duration)}
async function intro(text,t){ensureFlames();clearParticles();$('book')?.classList.add('hidden');$('cauldron').classList.remove('hidden');$('ceremony').dataset.animation='cauldron';intensity(1);text.textContent=t.opening1;text.className='ceremonyText narrative-line';shower('ember',16,true);await sleep(1800);await showLine(text,t.opening2,1750);$('cauldron').classList.add('awake');await showLine(text,t.opening3,1900,'narrative-line emphasis-soft');text.classList.add('fade-out');await sleep(420);text.textContent='';text.className='ceremonyText';await sleep(250)}
async function absorbMessage(text){text.classList.remove('message-reveal');text.classList.add('absorbing');shower('spark',14,true);await sleep(900);text.textContent='';text.className='ceremonyText';await sleep(180)}
async function finalSequence(text,customFinal,t){const c=$('cauldron');c.classList.remove('power-1','power-2','power-3','power-4');c.classList.add('finale');text.classList.add('fade-out');await sleep(420);text.textContent='';shower('ember',32,false);await sleep(650);await showLine(text,t.collective,2300,'final-step collective-line');await showLine(text,customFinal||'Merci d’avoir partagé un morceau de votre journée.',3000,'final-step grand-final-message');c.classList.add('bursting');shower('star',48,true);shower('confetti',44,true);await sleep(1200);await showLine(text,t.signature,2600,'grand-final');text.classList.add('fade-out');await sleep(450);text.textContent='';c.classList.remove('finale','bursting');c.classList.add('calm');await sleep(750);text.textContent=t.closing;text.className='ceremonyText closing-line';shower('last-spark',1,true);await sleep(4200)}
async function play(){if(running||!momentId)return;running=true;const started=Date.now(),ceremony=$('ceremony'),text=$('ceremonyText');ceremony.classList.remove('hidden');ceremony.classList.add('cinematic-cauldron');$('replay').classList.add('hidden');$('closeCeremony').classList.add('hidden');text.className='ceremonyText';try{const {moment,items}=await readData(),slides=buildSlides(items),target=targetDuration(items.length),t={...defaultTexts,...(moment.ceremonyTexts||{})};await intro(text,t);if(!slides.length){text.textContent='Même sans mot déposé, ce moment rappelle que le lien existe.';text.classList.add('message-reveal');await sleep(3400);await absorbMessage(text)}else{for(let i=0;i<slides.length;i++){const slide=slides[i];await react(i,slides.length);text.textContent=slide.text;text.className='ceremonyText message-reveal message-card';await sleep(slideDuration(slide,slides.length,target));await absorbMessage(text)}}await sleep(400);await finalSequence(text,moment.finalText,t);const remaining=target-(Date.now()-started);if(remaining>0)await sleep(remaining)}catch(e){console.error(e);text.textContent='La cérémonie n’a pas pu se charger. Réessaie dans un instant.'}finally{running=false;$('replay').classList.remove('hidden');$('closeCeremony').classList.remove('hidden');$('cauldron').classList.remove('awake','power-1','power-2','power-3','power-4','react-left','react-right','finale','bursting','calm')}}
document.addEventListener('click',e=>{const id=e.target?.id;if(id==='playFinal'||id==='replay'){e.preventDefault();e.stopImmediatePropagation();play()}},true);
$('closeCeremony')?.addEventListener('click',e=>{if(!running){e.preventDefault();e.stopImmediatePropagation();$('ceremony').classList.add('hidden');clearParticles()}},true);